name: heart-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas>=1.5
      - scikit-learn>=1.3.0  # scikit-learn 1.5.2 masih belum rilis stabil saat ini
      - mlflow>=2.19
      - numpy>=1.26
      - pyyaml
